package cn.zm.trip.web.dao;

import cn.zm.trip.web.domain.Hotel;
import cn.zm.trip.web.domain.HotelExample;
import java.util.List;

public interface HotelDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_hotel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_hotel
     *
     * @mbg.generated
     */
    int insert(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_hotel
     *
     * @mbg.generated
     */
    int insertSelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_hotel
     *
     * @mbg.generated
     */
    List<Hotel> selectByExampleWithBLOBs(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_hotel
     *
     * @mbg.generated
     */
    List<Hotel> selectByExample(HotelExample example);

    List<Hotel> hotelPointSearch(Hotel hotel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_hotel
     *
     * @mbg.generated
     */
    Hotel selectByPrimaryKey(Integer hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_hotel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_hotel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_hotel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Hotel record);
}