package cn.zm.trip.web.dao;

import cn.zm.trip.web.domain.Traffic;
import cn.zm.trip.web.domain.TrafficExample;
import java.util.List;

public interface TrafficMapepr {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer tpTid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    int insert(Traffic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    int insertSelective(Traffic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    List<Traffic> selectByExample(TrafficExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    Traffic selectByPrimaryKey(Integer tpTid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Traffic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Traffic record);
}