package cn.zm.trip.web.dao;

import cn.zm.trip.web.domain.ViewPoint;
import cn.zm.trip.web.domain.ViewPointExample;
import java.util.List;

public interface ViewPointDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer tpVid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    int insert(ViewPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    int insertSelective(ViewPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    List<ViewPoint> selectByExampleWithBLOBs(ViewPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    List<ViewPoint> selectByExample(ViewPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    ViewPoint selectByPrimaryKey(Integer tpVid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ViewPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ViewPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ViewPoint record);
}