package cn.zm.trip.web.domain;

import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Component
public class ForumExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_forum
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_forum
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_forum
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_forum
     *
     * @mbg.generated
     */
    public ForumExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_forum
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_forum
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_forum
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_forum
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_forum
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_forum
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_forum
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_forum
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_forum
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_forum
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_forum
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTpFidIsNull() {
            addCriterion("tp_fid is null");
            return (Criteria) this;
        }

        public Criteria andTpFidIsNotNull() {
            addCriterion("tp_fid is not null");
            return (Criteria) this;
        }

        public Criteria andTpFidEqualTo(Integer value) {
            addCriterion("tp_fid =", value, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFidNotEqualTo(Integer value) {
            addCriterion("tp_fid <>", value, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFidGreaterThan(Integer value) {
            addCriterion("tp_fid >", value, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFidGreaterThanOrEqualTo(Integer value) {
            addCriterion("tp_fid >=", value, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFidLessThan(Integer value) {
            addCriterion("tp_fid <", value, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFidLessThanOrEqualTo(Integer value) {
            addCriterion("tp_fid <=", value, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFidIn(List<Integer> values) {
            addCriterion("tp_fid in", values, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFidNotIn(List<Integer> values) {
            addCriterion("tp_fid not in", values, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFidBetween(Integer value1, Integer value2) {
            addCriterion("tp_fid between", value1, value2, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFidNotBetween(Integer value1, Integer value2) {
            addCriterion("tp_fid not between", value1, value2, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpAuthorIdIsNull() {
            addCriterion("tp_author_id is null");
            return (Criteria) this;
        }

        public Criteria andTpAuthorIdIsNotNull() {
            addCriterion("tp_author_id is not null");
            return (Criteria) this;
        }

        public Criteria andTpAuthorIdEqualTo(Integer value) {
            addCriterion("tp_author_id =", value, "tpAuthorId");
            return (Criteria) this;
        }

        public Criteria andTpAuthorIdNotEqualTo(Integer value) {
            addCriterion("tp_author_id <>", value, "tpAuthorId");
            return (Criteria) this;
        }

        public Criteria andTpAuthorIdGreaterThan(Integer value) {
            addCriterion("tp_author_id >", value, "tpAuthorId");
            return (Criteria) this;
        }

        public Criteria andTpAuthorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tp_author_id >=", value, "tpAuthorId");
            return (Criteria) this;
        }

        public Criteria andTpAuthorIdLessThan(Integer value) {
            addCriterion("tp_author_id <", value, "tpAuthorId");
            return (Criteria) this;
        }

        public Criteria andTpAuthorIdLessThanOrEqualTo(Integer value) {
            addCriterion("tp_author_id <=", value, "tpAuthorId");
            return (Criteria) this;
        }

        public Criteria andTpAuthorIdIn(List<Integer> values) {
            addCriterion("tp_author_id in", values, "tpAuthorId");
            return (Criteria) this;
        }

        public Criteria andTpAuthorIdNotIn(List<Integer> values) {
            addCriterion("tp_author_id not in", values, "tpAuthorId");
            return (Criteria) this;
        }

        public Criteria andTpAuthorIdBetween(Integer value1, Integer value2) {
            addCriterion("tp_author_id between", value1, value2, "tpAuthorId");
            return (Criteria) this;
        }

        public Criteria andTpAuthorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tp_author_id not between", value1, value2, "tpAuthorId");
            return (Criteria) this;
        }

        public Criteria andTpAuthorIsNull() {
            addCriterion("tp_author is null");
            return (Criteria) this;
        }

        public Criteria andTpAuthorIsNotNull() {
            addCriterion("tp_author is not null");
            return (Criteria) this;
        }

        public Criteria andTpAuthorEqualTo(String value) {
            addCriterion("tp_author =", value, "tpAuthor");
            return (Criteria) this;
        }

        public Criteria andTpAuthorNotEqualTo(String value) {
            addCriterion("tp_author <>", value, "tpAuthor");
            return (Criteria) this;
        }

        public Criteria andTpAuthorGreaterThan(String value) {
            addCriterion("tp_author >", value, "tpAuthor");
            return (Criteria) this;
        }

        public Criteria andTpAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("tp_author >=", value, "tpAuthor");
            return (Criteria) this;
        }

        public Criteria andTpAuthorLessThan(String value) {
            addCriterion("tp_author <", value, "tpAuthor");
            return (Criteria) this;
        }

        public Criteria andTpAuthorLessThanOrEqualTo(String value) {
            addCriterion("tp_author <=", value, "tpAuthor");
            return (Criteria) this;
        }

        public Criteria andTpAuthorLike(String value) {
            addCriterion("tp_author like", value, "tpAuthor");
            return (Criteria) this;
        }

        public Criteria andTpAuthorNotLike(String value) {
            addCriterion("tp_author not like", value, "tpAuthor");
            return (Criteria) this;
        }

        public Criteria andTpAuthorIn(List<String> values) {
            addCriterion("tp_author in", values, "tpAuthor");
            return (Criteria) this;
        }

        public Criteria andTpAuthorNotIn(List<String> values) {
            addCriterion("tp_author not in", values, "tpAuthor");
            return (Criteria) this;
        }

        public Criteria andTpAuthorBetween(String value1, String value2) {
            addCriterion("tp_author between", value1, value2, "tpAuthor");
            return (Criteria) this;
        }

        public Criteria andTpAuthorNotBetween(String value1, String value2) {
            addCriterion("tp_author not between", value1, value2, "tpAuthor");
            return (Criteria) this;
        }

        public Criteria andTpTitleIsNull() {
            addCriterion("tp_title is null");
            return (Criteria) this;
        }

        public Criteria andTpTitleIsNotNull() {
            addCriterion("tp_title is not null");
            return (Criteria) this;
        }

        public Criteria andTpTitleEqualTo(String value) {
            addCriterion("tp_title =", value, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleNotEqualTo(String value) {
            addCriterion("tp_title <>", value, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleGreaterThan(String value) {
            addCriterion("tp_title >", value, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleGreaterThanOrEqualTo(String value) {
            addCriterion("tp_title >=", value, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleLessThan(String value) {
            addCriterion("tp_title <", value, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleLessThanOrEqualTo(String value) {
            addCriterion("tp_title <=", value, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleLike(String value) {
            addCriterion("tp_title like", value, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleNotLike(String value) {
            addCriterion("tp_title not like", value, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleIn(List<String> values) {
            addCriterion("tp_title in", values, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleNotIn(List<String> values) {
            addCriterion("tp_title not in", values, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleBetween(String value1, String value2) {
            addCriterion("tp_title between", value1, value2, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleNotBetween(String value1, String value2) {
            addCriterion("tp_title not between", value1, value2, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpSubTitleIsNull() {
            addCriterion("tp_sub_title is null");
            return (Criteria) this;
        }

        public Criteria andTpSubTitleIsNotNull() {
            addCriterion("tp_sub_title is not null");
            return (Criteria) this;
        }

        public Criteria andTpSubTitleEqualTo(String value) {
            addCriterion("tp_sub_title =", value, "tpSubTitle");
            return (Criteria) this;
        }

        public Criteria andTpSubTitleNotEqualTo(String value) {
            addCriterion("tp_sub_title <>", value, "tpSubTitle");
            return (Criteria) this;
        }

        public Criteria andTpSubTitleGreaterThan(String value) {
            addCriterion("tp_sub_title >", value, "tpSubTitle");
            return (Criteria) this;
        }

        public Criteria andTpSubTitleGreaterThanOrEqualTo(String value) {
            addCriterion("tp_sub_title >=", value, "tpSubTitle");
            return (Criteria) this;
        }

        public Criteria andTpSubTitleLessThan(String value) {
            addCriterion("tp_sub_title <", value, "tpSubTitle");
            return (Criteria) this;
        }

        public Criteria andTpSubTitleLessThanOrEqualTo(String value) {
            addCriterion("tp_sub_title <=", value, "tpSubTitle");
            return (Criteria) this;
        }

        public Criteria andTpSubTitleLike(String value) {
            addCriterion("tp_sub_title like", value, "tpSubTitle");
            return (Criteria) this;
        }

        public Criteria andTpSubTitleNotLike(String value) {
            addCriterion("tp_sub_title not like", value, "tpSubTitle");
            return (Criteria) this;
        }

        public Criteria andTpSubTitleIn(List<String> values) {
            addCriterion("tp_sub_title in", values, "tpSubTitle");
            return (Criteria) this;
        }

        public Criteria andTpSubTitleNotIn(List<String> values) {
            addCriterion("tp_sub_title not in", values, "tpSubTitle");
            return (Criteria) this;
        }

        public Criteria andTpSubTitleBetween(String value1, String value2) {
            addCriterion("tp_sub_title between", value1, value2, "tpSubTitle");
            return (Criteria) this;
        }

        public Criteria andTpSubTitleNotBetween(String value1, String value2) {
            addCriterion("tp_sub_title not between", value1, value2, "tpSubTitle");
            return (Criteria) this;
        }

        public Criteria andTpIssueTimeIsNull() {
            addCriterion("tp_issue_time is null");
            return (Criteria) this;
        }

        public Criteria andTpIssueTimeIsNotNull() {
            addCriterion("tp_issue_time is not null");
            return (Criteria) this;
        }

        public Criteria andTpIssueTimeEqualTo(Date value) {
            addCriterion("tp_issue_time =", value, "tpIssueTime");
            return (Criteria) this;
        }

        public Criteria andTpIssueTimeNotEqualTo(Date value) {
            addCriterion("tp_issue_time <>", value, "tpIssueTime");
            return (Criteria) this;
        }

        public Criteria andTpIssueTimeGreaterThan(Date value) {
            addCriterion("tp_issue_time >", value, "tpIssueTime");
            return (Criteria) this;
        }

        public Criteria andTpIssueTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("tp_issue_time >=", value, "tpIssueTime");
            return (Criteria) this;
        }

        public Criteria andTpIssueTimeLessThan(Date value) {
            addCriterion("tp_issue_time <", value, "tpIssueTime");
            return (Criteria) this;
        }

        public Criteria andTpIssueTimeLessThanOrEqualTo(Date value) {
            addCriterion("tp_issue_time <=", value, "tpIssueTime");
            return (Criteria) this;
        }

        public Criteria andTpIssueTimeIn(List<Date> values) {
            addCriterion("tp_issue_time in", values, "tpIssueTime");
            return (Criteria) this;
        }

        public Criteria andTpIssueTimeNotIn(List<Date> values) {
            addCriterion("tp_issue_time not in", values, "tpIssueTime");
            return (Criteria) this;
        }

        public Criteria andTpIssueTimeBetween(Date value1, Date value2) {
            addCriterion("tp_issue_time between", value1, value2, "tpIssueTime");
            return (Criteria) this;
        }

        public Criteria andTpIssueTimeNotBetween(Date value1, Date value2) {
            addCriterion("tp_issue_time not between", value1, value2, "tpIssueTime");
            return (Criteria) this;
        }

        public Criteria andTpTagIsNull() {
            addCriterion("tp_tag is null");
            return (Criteria) this;
        }

        public Criteria andTpTagIsNotNull() {
            addCriterion("tp_tag is not null");
            return (Criteria) this;
        }

        public Criteria andTpTagEqualTo(String value) {
            addCriterion("tp_tag =", value, "tpTag");
            return (Criteria) this;
        }

        public Criteria andTpTagNotEqualTo(String value) {
            addCriterion("tp_tag <>", value, "tpTag");
            return (Criteria) this;
        }

        public Criteria andTpTagGreaterThan(String value) {
            addCriterion("tp_tag >", value, "tpTag");
            return (Criteria) this;
        }

        public Criteria andTpTagGreaterThanOrEqualTo(String value) {
            addCriterion("tp_tag >=", value, "tpTag");
            return (Criteria) this;
        }

        public Criteria andTpTagLessThan(String value) {
            addCriterion("tp_tag <", value, "tpTag");
            return (Criteria) this;
        }

        public Criteria andTpTagLessThanOrEqualTo(String value) {
            addCriterion("tp_tag <=", value, "tpTag");
            return (Criteria) this;
        }

        public Criteria andTpTagLike(String value) {
            addCriterion("tp_tag like", value, "tpTag");
            return (Criteria) this;
        }

        public Criteria andTpTagNotLike(String value) {
            addCriterion("tp_tag not like", value, "tpTag");
            return (Criteria) this;
        }

        public Criteria andTpTagIn(List<String> values) {
            addCriterion("tp_tag in", values, "tpTag");
            return (Criteria) this;
        }

        public Criteria andTpTagNotIn(List<String> values) {
            addCriterion("tp_tag not in", values, "tpTag");
            return (Criteria) this;
        }

        public Criteria andTpTagBetween(String value1, String value2) {
            addCriterion("tp_tag between", value1, value2, "tpTag");
            return (Criteria) this;
        }

        public Criteria andTpTagNotBetween(String value1, String value2) {
            addCriterion("tp_tag not between", value1, value2, "tpTag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_forum
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_forum
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}