package cn.zm.trip.web.domain;

import org.springframework.stereotype.Component;

import java.util.Date;

@Component
public class Forum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_forum.tp_fid
     *
     * @mbg.generated
     */
    private Integer tpFid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_forum.tp_author_id
     *
     * @mbg.generated
     */
    private Integer tpAuthorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_forum.tp_author
     *
     * @mbg.generated
     */
    private String tpAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_forum.tp_title
     *
     * @mbg.generated
     */
    private String tpTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_forum.tp_sub_title
     *
     * @mbg.generated
     */
    private String tpSubTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_forum.tp_issue_time
     *
     * @mbg.generated
     */
    private Date tpIssueTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_forum.tp_tag
     *
     * @mbg.generated
     */
    private String tpTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_forum.tp_tcontent
     *
     * @mbg.generated
     */
    private String tpTcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_forum.tp_fid
     *
     * @return the value of tp_forum.tp_fid
     *
     * @mbg.generated
     */
    public Integer getTpFid() {
        return tpFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_forum.tp_fid
     *
     * @param tpFid the value for tp_forum.tp_fid
     *
     * @mbg.generated
     */
    public void setTpFid(Integer tpFid) {
        this.tpFid = tpFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_forum.tp_author_id
     *
     * @return the value of tp_forum.tp_author_id
     *
     * @mbg.generated
     */
    public Integer getTpAuthorId() {
        return tpAuthorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_forum.tp_author_id
     *
     * @param tpAuthorId the value for tp_forum.tp_author_id
     *
     * @mbg.generated
     */
    public void setTpAuthorId(Integer tpAuthorId) {
        this.tpAuthorId = tpAuthorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_forum.tp_author
     *
     * @return the value of tp_forum.tp_author
     *
     * @mbg.generated
     */
    public String getTpAuthor() {
        return tpAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_forum.tp_author
     *
     * @param tpAuthor the value for tp_forum.tp_author
     *
     * @mbg.generated
     */
    public void setTpAuthor(String tpAuthor) {
        this.tpAuthor = tpAuthor == null ? null : tpAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_forum.tp_title
     *
     * @return the value of tp_forum.tp_title
     *
     * @mbg.generated
     */
    public String getTpTitle() {
        return tpTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_forum.tp_title
     *
     * @param tpTitle the value for tp_forum.tp_title
     *
     * @mbg.generated
     */
    public void setTpTitle(String tpTitle) {
        this.tpTitle = tpTitle == null ? null : tpTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_forum.tp_sub_title
     *
     * @return the value of tp_forum.tp_sub_title
     *
     * @mbg.generated
     */
    public String getTpSubTitle() {
        return tpSubTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_forum.tp_sub_title
     *
     * @param tpSubTitle the value for tp_forum.tp_sub_title
     *
     * @mbg.generated
     */
    public void setTpSubTitle(String tpSubTitle) {
        this.tpSubTitle = tpSubTitle == null ? null : tpSubTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_forum.tp_issue_time
     *
     * @return the value of tp_forum.tp_issue_time
     *
     * @mbg.generated
     */
    public Date getTpIssueTime() {
        return tpIssueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_forum.tp_issue_time
     *
     * @param tpIssueTime the value for tp_forum.tp_issue_time
     *
     * @mbg.generated
     */
    public void setTpIssueTime(Date tpIssueTime) {
        this.tpIssueTime = tpIssueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_forum.tp_tag
     *
     * @return the value of tp_forum.tp_tag
     *
     * @mbg.generated
     */
    public String getTpTag() {
        return tpTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_forum.tp_tag
     *
     * @param tpTag the value for tp_forum.tp_tag
     *
     * @mbg.generated
     */
    public void setTpTag(String tpTag) {
        this.tpTag = tpTag == null ? null : tpTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_forum.tp_tcontent
     *
     * @return the value of tp_forum.tp_tcontent
     *
     * @mbg.generated
     */
    public String getTpTcontent() {
        return tpTcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_forum.tp_tcontent
     *
     * @param tpTcontent the value for tp_forum.tp_tcontent
     *
     * @mbg.generated
     */
    public void setTpTcontent(String tpTcontent) {
        this.tpTcontent = tpTcontent == null ? null : tpTcontent.trim();
    }
}