package cn.zm.trip.web.domain;

public class Hotel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_hotel.hid
     *
     * @mbg.generated
     */
    private Integer hid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_hotel.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_hotel.local
     *
     * @mbg.generated
     */
    private String local;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_hotel.house_type
     *
     * @mbg.generated
     */
    private String houseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_hotel.bed_type
     *
     * @mbg.generated
     */
    private String bedType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_hotel.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_hotel.people_num
     *
     * @mbg.generated
     */
    private Integer peopleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_hotel.zip
     *
     * @mbg.generated
     */
    private String zip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_hotel.house_size
     *
     * @mbg.generated
     */
    private String houseSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_hotel.price
     *
     * @mbg.generated
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_hotel.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_hotel.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_hotel.hid
     *
     * @return the value of tp_hotel.hid
     *
     * @mbg.generated
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_hotel.hid
     *
     * @param hid the value for tp_hotel.hid
     *
     * @mbg.generated
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_hotel.title
     *
     * @return the value of tp_hotel.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_hotel.title
     *
     * @param title the value for tp_hotel.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_hotel.local
     *
     * @return the value of tp_hotel.local
     *
     * @mbg.generated
     */
    public String getLocal() {
        return local;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_hotel.local
     *
     * @param local the value for tp_hotel.local
     *
     * @mbg.generated
     */
    public void setLocal(String local) {
        this.local = local == null ? null : local.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_hotel.house_type
     *
     * @return the value of tp_hotel.house_type
     *
     * @mbg.generated
     */
    public String getHouseType() {
        return houseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_hotel.house_type
     *
     * @param houseType the value for tp_hotel.house_type
     *
     * @mbg.generated
     */
    public void setHouseType(String houseType) {
        this.houseType = houseType == null ? null : houseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_hotel.bed_type
     *
     * @return the value of tp_hotel.bed_type
     *
     * @mbg.generated
     */
    public String getBedType() {
        return bedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_hotel.bed_type
     *
     * @param bedType the value for tp_hotel.bed_type
     *
     * @mbg.generated
     */
    public void setBedType(String bedType) {
        this.bedType = bedType == null ? null : bedType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_hotel.phone
     *
     * @return the value of tp_hotel.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_hotel.phone
     *
     * @param phone the value for tp_hotel.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_hotel.people_num
     *
     * @return the value of tp_hotel.people_num
     *
     * @mbg.generated
     */
    public Integer getPeopleNum() {
        return peopleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_hotel.people_num
     *
     * @param peopleNum the value for tp_hotel.people_num
     *
     * @mbg.generated
     */
    public void setPeopleNum(Integer peopleNum) {
        this.peopleNum = peopleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_hotel.zip
     *
     * @return the value of tp_hotel.zip
     *
     * @mbg.generated
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_hotel.zip
     *
     * @param zip the value for tp_hotel.zip
     *
     * @mbg.generated
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_hotel.house_size
     *
     * @return the value of tp_hotel.house_size
     *
     * @mbg.generated
     */
    public String getHouseSize() {
        return houseSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_hotel.house_size
     *
     * @param houseSize the value for tp_hotel.house_size
     *
     * @mbg.generated
     */
    public void setHouseSize(String houseSize) {
        this.houseSize = houseSize == null ? null : houseSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_hotel.price
     *
     * @return the value of tp_hotel.price
     *
     * @mbg.generated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_hotel.price
     *
     * @param price the value for tp_hotel.price
     *
     * @mbg.generated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_hotel.img_url
     *
     * @return the value of tp_hotel.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_hotel.img_url
     *
     * @param imgUrl the value for tp_hotel.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_hotel.content
     *
     * @return the value of tp_hotel.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_hotel.content
     *
     * @param content the value for tp_hotel.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}