package cn.zm.trip.web.domain;

import java.util.ArrayList;
import java.util.List;

public class TrafficExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    public TrafficExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTpTidIsNull() {
            addCriterion("tp_Tid is null");
            return (Criteria) this;
        }

        public Criteria andTpTidIsNotNull() {
            addCriterion("tp_Tid is not null");
            return (Criteria) this;
        }

        public Criteria andTpTidEqualTo(Integer value) {
            addCriterion("tp_Tid =", value, "tpTid");
            return (Criteria) this;
        }

        public Criteria andTpTidNotEqualTo(Integer value) {
            addCriterion("tp_Tid <>", value, "tpTid");
            return (Criteria) this;
        }

        public Criteria andTpTidGreaterThan(Integer value) {
            addCriterion("tp_Tid >", value, "tpTid");
            return (Criteria) this;
        }

        public Criteria andTpTidGreaterThanOrEqualTo(Integer value) {
            addCriterion("tp_Tid >=", value, "tpTid");
            return (Criteria) this;
        }

        public Criteria andTpTidLessThan(Integer value) {
            addCriterion("tp_Tid <", value, "tpTid");
            return (Criteria) this;
        }

        public Criteria andTpTidLessThanOrEqualTo(Integer value) {
            addCriterion("tp_Tid <=", value, "tpTid");
            return (Criteria) this;
        }

        public Criteria andTpTidIn(List<Integer> values) {
            addCriterion("tp_Tid in", values, "tpTid");
            return (Criteria) this;
        }

        public Criteria andTpTidNotIn(List<Integer> values) {
            addCriterion("tp_Tid not in", values, "tpTid");
            return (Criteria) this;
        }

        public Criteria andTpTidBetween(Integer value1, Integer value2) {
            addCriterion("tp_Tid between", value1, value2, "tpTid");
            return (Criteria) this;
        }

        public Criteria andTpTidNotBetween(Integer value1, Integer value2) {
            addCriterion("tp_Tid not between", value1, value2, "tpTid");
            return (Criteria) this;
        }

        public Criteria andTpTypeIsNull() {
            addCriterion("tp_type is null");
            return (Criteria) this;
        }

        public Criteria andTpTypeIsNotNull() {
            addCriterion("tp_type is not null");
            return (Criteria) this;
        }

        public Criteria andTpTypeEqualTo(String value) {
            addCriterion("tp_type =", value, "tpType");
            return (Criteria) this;
        }

        public Criteria andTpTypeNotEqualTo(String value) {
            addCriterion("tp_type <>", value, "tpType");
            return (Criteria) this;
        }

        public Criteria andTpTypeGreaterThan(String value) {
            addCriterion("tp_type >", value, "tpType");
            return (Criteria) this;
        }

        public Criteria andTpTypeGreaterThanOrEqualTo(String value) {
            addCriterion("tp_type >=", value, "tpType");
            return (Criteria) this;
        }

        public Criteria andTpTypeLessThan(String value) {
            addCriterion("tp_type <", value, "tpType");
            return (Criteria) this;
        }

        public Criteria andTpTypeLessThanOrEqualTo(String value) {
            addCriterion("tp_type <=", value, "tpType");
            return (Criteria) this;
        }

        public Criteria andTpTypeLike(String value) {
            addCriterion("tp_type like", value, "tpType");
            return (Criteria) this;
        }

        public Criteria andTpTypeNotLike(String value) {
            addCriterion("tp_type not like", value, "tpType");
            return (Criteria) this;
        }

        public Criteria andTpTypeIn(List<String> values) {
            addCriterion("tp_type in", values, "tpType");
            return (Criteria) this;
        }

        public Criteria andTpTypeNotIn(List<String> values) {
            addCriterion("tp_type not in", values, "tpType");
            return (Criteria) this;
        }

        public Criteria andTpTypeBetween(String value1, String value2) {
            addCriterion("tp_type between", value1, value2, "tpType");
            return (Criteria) this;
        }

        public Criteria andTpTypeNotBetween(String value1, String value2) {
            addCriterion("tp_type not between", value1, value2, "tpType");
            return (Criteria) this;
        }

        public Criteria andTpCurrentIsNull() {
            addCriterion("tp_current is null");
            return (Criteria) this;
        }

        public Criteria andTpCurrentIsNotNull() {
            addCriterion("tp_current is not null");
            return (Criteria) this;
        }

        public Criteria andTpCurrentEqualTo(String value) {
            addCriterion("tp_current =", value, "tpCurrent");
            return (Criteria) this;
        }

        public Criteria andTpCurrentNotEqualTo(String value) {
            addCriterion("tp_current <>", value, "tpCurrent");
            return (Criteria) this;
        }

        public Criteria andTpCurrentGreaterThan(String value) {
            addCriterion("tp_current >", value, "tpCurrent");
            return (Criteria) this;
        }

        public Criteria andTpCurrentGreaterThanOrEqualTo(String value) {
            addCriterion("tp_current >=", value, "tpCurrent");
            return (Criteria) this;
        }

        public Criteria andTpCurrentLessThan(String value) {
            addCriterion("tp_current <", value, "tpCurrent");
            return (Criteria) this;
        }

        public Criteria andTpCurrentLessThanOrEqualTo(String value) {
            addCriterion("tp_current <=", value, "tpCurrent");
            return (Criteria) this;
        }

        public Criteria andTpCurrentLike(String value) {
            addCriterion("tp_current like", value, "tpCurrent");
            return (Criteria) this;
        }

        public Criteria andTpCurrentNotLike(String value) {
            addCriterion("tp_current not like", value, "tpCurrent");
            return (Criteria) this;
        }

        public Criteria andTpCurrentIn(List<String> values) {
            addCriterion("tp_current in", values, "tpCurrent");
            return (Criteria) this;
        }

        public Criteria andTpCurrentNotIn(List<String> values) {
            addCriterion("tp_current not in", values, "tpCurrent");
            return (Criteria) this;
        }

        public Criteria andTpCurrentBetween(String value1, String value2) {
            addCriterion("tp_current between", value1, value2, "tpCurrent");
            return (Criteria) this;
        }

        public Criteria andTpCurrentNotBetween(String value1, String value2) {
            addCriterion("tp_current not between", value1, value2, "tpCurrent");
            return (Criteria) this;
        }

        public Criteria andTpDestinationIsNull() {
            addCriterion("tp_destination is null");
            return (Criteria) this;
        }

        public Criteria andTpDestinationIsNotNull() {
            addCriterion("tp_destination is not null");
            return (Criteria) this;
        }

        public Criteria andTpDestinationEqualTo(String value) {
            addCriterion("tp_destination =", value, "tpDestination");
            return (Criteria) this;
        }

        public Criteria andTpDestinationNotEqualTo(String value) {
            addCriterion("tp_destination <>", value, "tpDestination");
            return (Criteria) this;
        }

        public Criteria andTpDestinationGreaterThan(String value) {
            addCriterion("tp_destination >", value, "tpDestination");
            return (Criteria) this;
        }

        public Criteria andTpDestinationGreaterThanOrEqualTo(String value) {
            addCriterion("tp_destination >=", value, "tpDestination");
            return (Criteria) this;
        }

        public Criteria andTpDestinationLessThan(String value) {
            addCriterion("tp_destination <", value, "tpDestination");
            return (Criteria) this;
        }

        public Criteria andTpDestinationLessThanOrEqualTo(String value) {
            addCriterion("tp_destination <=", value, "tpDestination");
            return (Criteria) this;
        }

        public Criteria andTpDestinationLike(String value) {
            addCriterion("tp_destination like", value, "tpDestination");
            return (Criteria) this;
        }

        public Criteria andTpDestinationNotLike(String value) {
            addCriterion("tp_destination not like", value, "tpDestination");
            return (Criteria) this;
        }

        public Criteria andTpDestinationIn(List<String> values) {
            addCriterion("tp_destination in", values, "tpDestination");
            return (Criteria) this;
        }

        public Criteria andTpDestinationNotIn(List<String> values) {
            addCriterion("tp_destination not in", values, "tpDestination");
            return (Criteria) this;
        }

        public Criteria andTpDestinationBetween(String value1, String value2) {
            addCriterion("tp_destination between", value1, value2, "tpDestination");
            return (Criteria) this;
        }

        public Criteria andTpDestinationNotBetween(String value1, String value2) {
            addCriterion("tp_destination not between", value1, value2, "tpDestination");
            return (Criteria) this;
        }

        public Criteria andTpCurrentTimeIsNull() {
            addCriterion("tp_current_time is null");
            return (Criteria) this;
        }

        public Criteria andTpCurrentTimeIsNotNull() {
            addCriterion("tp_current_time is not null");
            return (Criteria) this;
        }

        public Criteria andTpCurrentTimeEqualTo(String value) {
            addCriterion("tp_current_time =", value, "tpCurrentTime");
            return (Criteria) this;
        }

        public Criteria andTpCurrentTimeNotEqualTo(String value) {
            addCriterion("tp_current_time <>", value, "tpCurrentTime");
            return (Criteria) this;
        }

        public Criteria andTpCurrentTimeGreaterThan(String value) {
            addCriterion("tp_current_time >", value, "tpCurrentTime");
            return (Criteria) this;
        }

        public Criteria andTpCurrentTimeGreaterThanOrEqualTo(String value) {
            addCriterion("tp_current_time >=", value, "tpCurrentTime");
            return (Criteria) this;
        }

        public Criteria andTpCurrentTimeLessThan(String value) {
            addCriterion("tp_current_time <", value, "tpCurrentTime");
            return (Criteria) this;
        }

        public Criteria andTpCurrentTimeLessThanOrEqualTo(String value) {
            addCriterion("tp_current_time <=", value, "tpCurrentTime");
            return (Criteria) this;
        }

        public Criteria andTpCurrentTimeLike(String value) {
            addCriterion("tp_current_time like", value, "tpCurrentTime");
            return (Criteria) this;
        }

        public Criteria andTpCurrentTimeNotLike(String value) {
            addCriterion("tp_current_time not like", value, "tpCurrentTime");
            return (Criteria) this;
        }

        public Criteria andTpCurrentTimeIn(List<String> values) {
            addCriterion("tp_current_time in", values, "tpCurrentTime");
            return (Criteria) this;
        }

        public Criteria andTpCurrentTimeNotIn(List<String> values) {
            addCriterion("tp_current_time not in", values, "tpCurrentTime");
            return (Criteria) this;
        }

        public Criteria andTpCurrentTimeBetween(String value1, String value2) {
            addCriterion("tp_current_time between", value1, value2, "tpCurrentTime");
            return (Criteria) this;
        }

        public Criteria andTpCurrentTimeNotBetween(String value1, String value2) {
            addCriterion("tp_current_time not between", value1, value2, "tpCurrentTime");
            return (Criteria) this;
        }

        public Criteria andTpArriveTimeIsNull() {
            addCriterion("tp_arrive_time is null");
            return (Criteria) this;
        }

        public Criteria andTpArriveTimeIsNotNull() {
            addCriterion("tp_arrive_time is not null");
            return (Criteria) this;
        }

        public Criteria andTpArriveTimeEqualTo(String value) {
            addCriterion("tp_arrive_time =", value, "tpArriveTime");
            return (Criteria) this;
        }

        public Criteria andTpArriveTimeNotEqualTo(String value) {
            addCriterion("tp_arrive_time <>", value, "tpArriveTime");
            return (Criteria) this;
        }

        public Criteria andTpArriveTimeGreaterThan(String value) {
            addCriterion("tp_arrive_time >", value, "tpArriveTime");
            return (Criteria) this;
        }

        public Criteria andTpArriveTimeGreaterThanOrEqualTo(String value) {
            addCriterion("tp_arrive_time >=", value, "tpArriveTime");
            return (Criteria) this;
        }

        public Criteria andTpArriveTimeLessThan(String value) {
            addCriterion("tp_arrive_time <", value, "tpArriveTime");
            return (Criteria) this;
        }

        public Criteria andTpArriveTimeLessThanOrEqualTo(String value) {
            addCriterion("tp_arrive_time <=", value, "tpArriveTime");
            return (Criteria) this;
        }

        public Criteria andTpArriveTimeLike(String value) {
            addCriterion("tp_arrive_time like", value, "tpArriveTime");
            return (Criteria) this;
        }

        public Criteria andTpArriveTimeNotLike(String value) {
            addCriterion("tp_arrive_time not like", value, "tpArriveTime");
            return (Criteria) this;
        }

        public Criteria andTpArriveTimeIn(List<String> values) {
            addCriterion("tp_arrive_time in", values, "tpArriveTime");
            return (Criteria) this;
        }

        public Criteria andTpArriveTimeNotIn(List<String> values) {
            addCriterion("tp_arrive_time not in", values, "tpArriveTime");
            return (Criteria) this;
        }

        public Criteria andTpArriveTimeBetween(String value1, String value2) {
            addCriterion("tp_arrive_time between", value1, value2, "tpArriveTime");
            return (Criteria) this;
        }

        public Criteria andTpArriveTimeNotBetween(String value1, String value2) {
            addCriterion("tp_arrive_time not between", value1, value2, "tpArriveTime");
            return (Criteria) this;
        }

        public Criteria andTpTpriceIsNull() {
            addCriterion("tp_tprice is null");
            return (Criteria) this;
        }

        public Criteria andTpTpriceIsNotNull() {
            addCriterion("tp_tprice is not null");
            return (Criteria) this;
        }

        public Criteria andTpTpriceEqualTo(String value) {
            addCriterion("tp_tprice =", value, "tpTprice");
            return (Criteria) this;
        }

        public Criteria andTpTpriceNotEqualTo(String value) {
            addCriterion("tp_tprice <>", value, "tpTprice");
            return (Criteria) this;
        }

        public Criteria andTpTpriceGreaterThan(String value) {
            addCriterion("tp_tprice >", value, "tpTprice");
            return (Criteria) this;
        }

        public Criteria andTpTpriceGreaterThanOrEqualTo(String value) {
            addCriterion("tp_tprice >=", value, "tpTprice");
            return (Criteria) this;
        }

        public Criteria andTpTpriceLessThan(String value) {
            addCriterion("tp_tprice <", value, "tpTprice");
            return (Criteria) this;
        }

        public Criteria andTpTpriceLessThanOrEqualTo(String value) {
            addCriterion("tp_tprice <=", value, "tpTprice");
            return (Criteria) this;
        }

        public Criteria andTpTpriceLike(String value) {
            addCriterion("tp_tprice like", value, "tpTprice");
            return (Criteria) this;
        }

        public Criteria andTpTpriceNotLike(String value) {
            addCriterion("tp_tprice not like", value, "tpTprice");
            return (Criteria) this;
        }

        public Criteria andTpTpriceIn(List<String> values) {
            addCriterion("tp_tprice in", values, "tpTprice");
            return (Criteria) this;
        }

        public Criteria andTpTpriceNotIn(List<String> values) {
            addCriterion("tp_tprice not in", values, "tpTprice");
            return (Criteria) this;
        }

        public Criteria andTpTpriceBetween(String value1, String value2) {
            addCriterion("tp_tprice between", value1, value2, "tpTprice");
            return (Criteria) this;
        }

        public Criteria andTpTpriceNotBetween(String value1, String value2) {
            addCriterion("tp_tprice not between", value1, value2, "tpTprice");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_traffic
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_traffic
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}