package cn.zm.trip.web.domain;

import org.springframework.stereotype.Component;

import java.util.Date;
@Component
public class ViewPoint {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_viewpoint.tp_vid
     *
     * @mbg.generated
     */
    private Integer tpVid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_viewpoint.tp_title
     *
     * @mbg.generated
     */
    private String tpTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_viewpoint.tp_vname
     *
     * @mbg.generated
     */
    private String tpVname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_viewpoint.tp_vtype
     *
     * @mbg.generated
     */
    private String tpVtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_viewpoint.tp_vpic
     *
     * @mbg.generated
     */
    private String tpVpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_viewpoint.tp_vphone
     *
     * @mbg.generated
     */
    private String tpVphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_viewpoint.tp_level
     *
     * @mbg.generated
     */
    private String tpLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_viewpoint.tp_price
     *
     * @mbg.generated
     */
    private Integer tpPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_viewpoint.tp_location
     *
     * @mbg.generated
     */
    private String tpLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_viewpoint.tp_zip
     *
     * @mbg.generated
     */
    private String tpZip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_viewpoint.tp_opentime
     *
     * @mbg.generated
     */
    private String tpOpentime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_viewpoint.tp_creatTime
     *
     * @mbg.generated
     */
    private Date tpCreattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_viewpoint.tp_vcontent
     *
     * @mbg.generated
     */
    private String tpVcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_viewpoint.tp_vid
     *
     * @return the value of tp_viewpoint.tp_vid
     *
     * @mbg.generated
     */
    public Integer getTpVid() {
        return tpVid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_viewpoint.tp_vid
     *
     * @param tpVid the value for tp_viewpoint.tp_vid
     *
     * @mbg.generated
     */
    public void setTpVid(Integer tpVid) {
        this.tpVid = tpVid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_viewpoint.tp_title
     *
     * @return the value of tp_viewpoint.tp_title
     *
     * @mbg.generated
     */
    public String getTpTitle() {
        return tpTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_viewpoint.tp_title
     *
     * @param tpTitle the value for tp_viewpoint.tp_title
     *
     * @mbg.generated
     */
    public void setTpTitle(String tpTitle) {
        this.tpTitle = tpTitle == null ? null : tpTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_viewpoint.tp_vname
     *
     * @return the value of tp_viewpoint.tp_vname
     *
     * @mbg.generated
     */
    public String getTpVname() {
        return tpVname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_viewpoint.tp_vname
     *
     * @param tpVname the value for tp_viewpoint.tp_vname
     *
     * @mbg.generated
     */
    public void setTpVname(String tpVname) {
        this.tpVname = tpVname == null ? null : tpVname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_viewpoint.tp_vtype
     *
     * @return the value of tp_viewpoint.tp_vtype
     *
     * @mbg.generated
     */
    public String getTpVtype() {
        return tpVtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_viewpoint.tp_vtype
     *
     * @param tpVtype the value for tp_viewpoint.tp_vtype
     *
     * @mbg.generated
     */
    public void setTpVtype(String tpVtype) {
        this.tpVtype = tpVtype == null ? null : tpVtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_viewpoint.tp_vpic
     *
     * @return the value of tp_viewpoint.tp_vpic
     *
     * @mbg.generated
     */
    public String getTpVpic() {
        return tpVpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_viewpoint.tp_vpic
     *
     * @param tpVpic the value for tp_viewpoint.tp_vpic
     *
     * @mbg.generated
     */
    public void setTpVpic(String tpVpic) {
        this.tpVpic = tpVpic == null ? null : tpVpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_viewpoint.tp_vphone
     *
     * @return the value of tp_viewpoint.tp_vphone
     *
     * @mbg.generated
     */
    public String getTpVphone() {
        return tpVphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_viewpoint.tp_vphone
     *
     * @param tpVphone the value for tp_viewpoint.tp_vphone
     *
     * @mbg.generated
     */
    public void setTpVphone(String tpVphone) {
        this.tpVphone = tpVphone == null ? null : tpVphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_viewpoint.tp_level
     *
     * @return the value of tp_viewpoint.tp_level
     *
     * @mbg.generated
     */
    public String getTpLevel() {
        return tpLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_viewpoint.tp_level
     *
     * @param tpLevel the value for tp_viewpoint.tp_level
     *
     * @mbg.generated
     */
    public void setTpLevel(String tpLevel) {
        this.tpLevel = tpLevel == null ? null : tpLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_viewpoint.tp_price
     *
     * @return the value of tp_viewpoint.tp_price
     *
     * @mbg.generated
     */
    public Integer getTpPrice() {
        return tpPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_viewpoint.tp_price
     *
     * @param tpPrice the value for tp_viewpoint.tp_price
     *
     * @mbg.generated
     */
    public void setTpPrice(Integer tpPrice) {
        this.tpPrice = tpPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_viewpoint.tp_location
     *
     * @return the value of tp_viewpoint.tp_location
     *
     * @mbg.generated
     */
    public String getTpLocation() {
        return tpLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_viewpoint.tp_location
     *
     * @param tpLocation the value for tp_viewpoint.tp_location
     *
     * @mbg.generated
     */
    public void setTpLocation(String tpLocation) {
        this.tpLocation = tpLocation == null ? null : tpLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_viewpoint.tp_zip
     *
     * @return the value of tp_viewpoint.tp_zip
     *
     * @mbg.generated
     */
    public String getTpZip() {
        return tpZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_viewpoint.tp_zip
     *
     * @param tpZip the value for tp_viewpoint.tp_zip
     *
     * @mbg.generated
     */
    public void setTpZip(String tpZip) {
        this.tpZip = tpZip == null ? null : tpZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_viewpoint.tp_opentime
     *
     * @return the value of tp_viewpoint.tp_opentime
     *
     * @mbg.generated
     */
    public String getTpOpentime() {
        return tpOpentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_viewpoint.tp_opentime
     *
     * @param tpOpentime the value for tp_viewpoint.tp_opentime
     *
     * @mbg.generated
     */
    public void setTpOpentime(String tpOpentime) {
        this.tpOpentime = tpOpentime == null ? null : tpOpentime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_viewpoint.tp_creatTime
     *
     * @return the value of tp_viewpoint.tp_creatTime
     *
     * @mbg.generated
     */
    public Date getTpCreattime() {
        return tpCreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_viewpoint.tp_creatTime
     *
     * @param tpCreattime the value for tp_viewpoint.tp_creatTime
     *
     * @mbg.generated
     */
    public void setTpCreattime(Date tpCreattime) {
        this.tpCreattime = tpCreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_viewpoint.tp_vcontent
     *
     * @return the value of tp_viewpoint.tp_vcontent
     *
     * @mbg.generated
     */
    public String getTpVcontent() {
        return tpVcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_viewpoint.tp_vcontent
     *
     * @param tpVcontent the value for tp_viewpoint.tp_vcontent
     *
     * @mbg.generated
     */
    public void setTpVcontent(String tpVcontent) {
        this.tpVcontent = tpVcontent == null ? null : tpVcontent.trim();
    }
}